# Generated by Django 4.2.13 on 2024-06-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.RemoveConstraint(
            model_name='log',
            name='unique_log',
        ),
        migrations.AddField(
            model_name='log',
            name='rewatch',
            field=models.BooleanField(default=False),
        ),
    ]
