# Generated by Django 4.2.13 on 2024-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_options_remove_log_unique_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='reviews_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='views_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
