# Generated by Django 4.2.13 on 2024-06-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_movie_reviews_total_alter_movie_views_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='priority',
        ),
    ]
