# Generated by Django 4.2.13 on 2024-06-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_watchlist_options_remove_watchlist_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='whatchlist',
            new_name='watchlists',
        ),
    ]
