# Generated by Django 4.2.13 on 2024-06-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_whatchlist_profile_watchlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
