# Generated by Django 4.2.13 on 2024-06-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_log_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review',
        ),
    ]
